import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { companionRelease, releaseBaseUrl, releasePageUrl } from "@/data/companionRelease";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BadgeCheck, CheckCircle2, ChevronLeft, Copy, Download as DownloadIcon, FileCheck2, Github, KeyRound, Laptop, ShieldCheck, Terminal, TriangleAlert } from "lucide-react";
import React from "react";
import { toast } from "sonner";

function Code({ children }: { children: string }) {
  return <div className="group relative overflow-x-auto rounded-xl border border-white/[0.08] bg-[#071016] p-3 pr-11"><code className="whitespace-pre font-mono text-[11px] leading-5 text-[#d9e8e2]">{children}</code><button onClick={() => navigator.clipboard.writeText(children).then(() => toast.success("Copied to clipboard"))} className="absolute right-2 top-2 grid h-7 w-7 place-items-center rounded-lg text-[#8ca1a1] transition-colors hover:bg-white/[0.08] hover:text-white" aria-label="Copy command"><Copy className="h-3.5 w-3.5" /></button></div>;
}

export function ReleaseTrustBadge({ published }: { published: boolean }) {
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.11em] ${published ? "border-[#b7f05a]/30 bg-[#b7f05a]/10 text-[#c9f784]" : "border-[#ffbc7d]/30 bg-[#ffbc7d]/10 text-[#ffd1a8]"}`}>{published ? <BadgeCheck className="h-3.5 w-3.5" /> : <TriangleAlert className="h-3.5 w-3.5" />}{published ? "signed release available" : "signed release pending"}</span>;
}

export default function Download() {
  const { isAuthenticated } = useAuth();
  const releaseStatus = trpc.release.status.useQuery(undefined, { enabled: isAuthenticated, refetchInterval: 60_000, retry: 1 });
  const release = releaseStatus.data;
  const isAvailable = release?.state === "available";
  const downloadUrlFor = (name: string) => release?.assets.find(asset => asset.name === name)?.downloadUrl ?? `${releaseBaseUrl}/${name}`;
  const verifyBlob = `cosign verify-blob --bundle <asset>.sigstore.json \\
  --certificate-identity-regexp '${companionRelease.workflowIdentity}' \\
  --certificate-oidc-issuer https://token.actions.githubusercontent.com <asset>`;
  return <main className="min-h-screen overflow-x-hidden bg-[#080f14] text-white"><div className="pointer-events-none fixed inset-0 opacity-70" style={{ backgroundImage: "radial-gradient(circle at 15% -10%, rgba(183,240,90,0.14), transparent 34%), radial-gradient(circle at 88% 8%, rgba(77,149,208,0.16), transparent 28%)" }} />
    <header className="relative mx-auto flex w-full max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><a href="/" className="flex items-center gap-2 text-sm font-extrabold tracking-[-0.04em] text-white"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#b7f05a] text-[#17220d]"><Terminal className="h-4 w-4" /></span>Autopilot Studio</a><a href="/setup" className="inline-flex items-center text-xs font-semibold text-[#bfe879] hover:text-[#d8ff96]">Open setup <ArrowRight className="ml-1.5 h-3.5 w-3.5" /></a></header>
    <div className="relative mx-auto max-w-6xl px-5 pb-14 pt-8 sm:px-8 sm:pt-16"><a href="/" className="inline-flex items-center text-xs text-[#9db0b1] transition-colors hover:text-white"><ChevronLeft className="mr-1 h-3.5 w-3.5" />Back to Studio</a><section className="mt-8 grid gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.17em] text-[#bfe879]">Local companion / distribution</p><h1 className="mt-4 max-w-3xl text-4xl font-extrabold tracking-[-0.065em] text-white sm:text-6xl">Keep Git local.<br /><span className="text-[#bfe879]">Keep every release verifiable.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-[#a7b7b6] sm:text-base">Autopilot Companion is a Node 20+ local CLI. It observes only high-level repository safety metadata, and does not upload source code, diffs, file names, remotes, or credentials.</p><div className="mt-7 flex flex-wrap gap-3"><a href="/setup"><Button className="h-10 rounded-xl bg-[#b7f05a] px-4 text-xs font-bold text-[#15200b] hover:bg-[#ccf584]"><KeyRound className="mr-1.5 h-4 w-4" />Pair a device</Button></a><a href={`https://github.com/${companionRelease.repository}`} target="_blank" rel="noreferrer"><Button variant="outline" className="h-10 rounded-xl border-white/[0.13] bg-white/[0.035] text-xs text-white hover:bg-white/[0.08]"><Github className="mr-1.5 h-4 w-4" />View source</Button></a></div></div><aside className="rounded-[28px] border border-[#b7f05a]/20 bg-[#0d181b]/90 p-5 shadow-2xl shadow-black/20"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.13em] text-[#8ba09d]">Release channel</p><p className="mt-2 text-lg font-bold text-white">{companionRelease.tag}</p></div><ReleaseTrustBadge published={isAvailable} /></div><p className="mt-4 text-xs leading-5 text-[#9dafad]">{!isAuthenticated ? "Sign in and connect GitHub to let Studio verify the expected signed release asset set before enabling downloads." : releaseStatus.isLoading ? "Checking GitHub for the expected signed release asset set…" : isAvailable ? "The expected published bundles, integrity files, and Sigstore bundles are all present. Download actions are active." : release?.state === "incomplete" ? "A release exists but does not yet contain the complete signed asset set. Download actions remain disabled." : releaseStatus.error ? "Release status could not be checked. Download actions remain disabled until Studio can verify the asset set." : "No completed signed release is available yet. Local artifacts are deliberately labeled unsigned; do not treat them as a published release."}</p><a href={release?.releaseUrl ?? releasePageUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex text-xs font-semibold text-[#c9f784] hover:text-[#dff8a5]">View GitHub release status <ArrowRight className="ml-1.5 h-3.5 w-3.5" /></a></aside></section>
      <section className="mt-12"><div className="flex flex-col justify-between gap-3 border-b border-white/[0.08] pb-4 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#829598]">Release assets</p><h2 className="mt-2 text-2xl font-bold tracking-[-0.05em] text-white">Choose your local bundle.</h2></div><p className="max-w-md text-xs leading-5 text-[#899d9d]">All bundles contain the same Node source package, license, manifest, and local-only executable entry point.</p></div><div className="mt-4 grid gap-4 md:grid-cols-3">{companionRelease.assets.map(asset => <article key={asset.platform} className="rounded-2xl border border-white/[0.08] bg-[#101a20]/80 p-5"><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/[0.06] text-[#bfe879]"><Laptop className="h-4 w-4" /></span><span className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#819599]">Node 20+</span></div><h3 className="mt-5 text-base font-bold text-white">{asset.platform}</h3><p className="mt-1 break-all font-mono text-[10px] leading-5 text-[#8fa3a4]">{asset.file}</p><a href={downloadUrlFor(asset.file)} aria-disabled={!isAvailable} onClick={event => { if (!isAvailable) { event.preventDefault(); toast.info("Studio will activate downloads after it verifies the complete signed release asset set."); } }} className={`mt-5 inline-flex h-9 w-full items-center justify-center rounded-xl text-xs font-semibold ${isAvailable ? "bg-[#b7f05a] text-[#17220d] hover:bg-[#cdf682]" : "cursor-not-allowed bg-white/[0.06] text-[#74898b]"}`}><DownloadIcon className="mr-1.5 h-3.5 w-3.5" />{isAvailable ? "Download signed bundle" : "Release pending"}</a><p className="mt-4 font-mono text-[9px] uppercase tracking-[0.1em] text-[#71878a]">Extract</p><div className="mt-2"><Code>{asset.install}</Code></div></article>)}</div></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-2"><article className="rounded-[24px] border border-[#b7f05a]/17 bg-[#b7f05a]/[0.045] p-5"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#c9f784]" /><h2 className="text-base font-bold text-white">What is in this release</h2></div><ul className="mt-3 space-y-2">{companionRelease.notes.map(note => <li key={note} className="flex gap-2 text-xs leading-5 text-[#a5b5af]"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#b7f05a]" />{note}</li>)}</ul></article><article className="rounded-[24px] border border-white/[0.08] bg-[#101a20]/75 p-5"><div className="flex items-center gap-2"><FileCheck2 className="h-4 w-4 text-[#bfe879]" /><h2 className="text-base font-bold text-white">1. Verify checksums</h2></div><p className="mt-2 text-xs leading-5 text-[#91a4a5]">Download <code className="rounded bg-white/[0.06] px-1 py-0.5 text-[#d5e4df]">SHA256SUMS</code> from the same release, then validate the archive before extracting it.</p><div className="mt-4"><Code>{"shasum -a 256 -c SHA256SUMS\n# Linux alternative: sha256sum -c SHA256SUMS"}</Code></div><div className="mt-3"><Code>{"Get-FileHash .\\autopilot-companion-1.0.0-windows-node20.zip -Algorithm SHA256"}</Code></div></article><article className="rounded-[24px] border border-white/[0.08] bg-[#101a20]/75 p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#8cc5ff]" /><h2 className="text-base font-bold text-white">2. Verify keyless signature</h2></div><p className="mt-2 text-xs leading-5 text-[#91a4a5]">Every published blob, including checksums and manifests, receives a Sigstore bundle from the tag workflow. This verification does not require a shared private key.</p><div className="mt-4"><Code>{verifyBlob}</Code></div></article></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><article className="rounded-[24px] border border-[#8cc5ff]/17 bg-[#8cc5ff]/[0.045] p-5"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#b3d9ff]" /><h2 className="text-base font-bold text-white">3. Verify GitHub provenance</h2></div><p className="mt-2 text-xs leading-5 text-[#9fb4bd]">GitHub also records a build provenance attestation for the release artifacts. Verify the downloaded file against this repository.</p><div className="mt-4"><Code>{`gh attestation verify <asset> -R ${companionRelease.repository}`}</Code></div></article><article className="rounded-[24px] border border-[#ffbc7d]/20 bg-[#ffbc7d]/[0.045] p-5"><div className="flex gap-3"><TriangleAlert className="mt-0.5 h-4 w-4 shrink-0 text-[#ffd1a8]" /><div><h2 className="text-base font-bold text-white">Development artifacts are unsigned</h2><p className="mt-2 text-xs leading-5 text-[#b7a191]">Running <code className="rounded bg-white/[0.06] px-1 py-0.5 text-[#f0d0b3]">pnpm companion:package</code> is useful for local testing only. It cannot fabricate a published signature, certificate, or GitHub provenance record.</p></div></div></article></section>
      <footer className="mt-12 border-t border-white/[0.08] pt-6 text-center text-xs leading-5 text-[#718588]">Release automation uses GitHub OIDC for keyless signing. Private signing keys, local device keys, pairing codes, and Git credentials are never embedded in these bundles.</footer>
    </div></main>;
}
