import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { deriveSetupMilestones } from "@shared/setupFlow";
import { Check, ChevronRight, CircleAlert, Copy, Github, KeyRound, Laptop, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import React, { useState } from "react";
import { toast } from "sonner";

export default function SetupWizard() {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const connection = trpc.github.connection.useQuery(undefined, { enabled: isAuthenticated });
  const repositories = trpc.github.repositories.useQuery(undefined, { enabled: isAuthenticated && Boolean(connection.data) });
  const dashboard = trpc.studio.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const monitoring = trpc.studio.monitoring.useQuery(undefined, { enabled: isAuthenticated && Boolean(connection.data) });
  const [label, setLabel] = useState("My local companion");
  const [pairing, setPairing] = useState<string | null>(null);
  const beginAuthorization = trpc.github.beginAuthorization.useMutation({ onMutate: () => sessionStorage.setItem("autopilot-github-authorizing", "1"), onSuccess: result => window.location.assign(result.authorizationUrl), onError: error => toast.error("GitHub authorization could not start", { description: error.message }) });
  const createPairing = trpc.companion.createPairing.useMutation({ onSuccess: result => setPairing(result.pairingCode), onError: error => toast.error("Pairing code could not be created", { description: error.message }) });
  const setSelected = trpc.github.setSelectedRepositories.useMutation({ onSuccess: () => { utils.github.repositories.invalidate(); toast.success("Repository scope saved"); }, onError: error => toast.error("Repository scope could not be saved", { description: error.message }) });
  const selected = (repositories.data ?? []).filter((repository: any) => repository.selected).map((repository: any) => repository.githubRepositoryId);
  const milestones = deriveSetupMilestones({ connected: Boolean(connection.data), selectedRepositories: selected.length, pairedDevices: dashboard.data?.devices?.length ?? 0, currentSnapshots: monitoring.data?.summary.currentSnapshots ?? 0, freshLocalStatuses: monitoring.data?.summary.freshLocalStatuses ?? 0 });
  const callbackUrl = `${window.location.origin}/api/github/callback`;
  const pairingCommand = pairing ? `pnpm companion pair ${window.location.origin} ${pairing} "${label}"` : "Create a one-time pairing code to unlock this step.";
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); toast.success("Copied to clipboard"); };

  return <div className="mx-auto max-w-[1080px] space-y-5"><header className="border-b border-white/[0.08] pb-6"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#82949a]">Guided setup / Local-first onboarding</p><h1 className="mt-2 text-2xl font-extrabold tracking-[-0.055em] text-white sm:text-[30px]">Set up your guardrails before automation.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#9faeaf]">Complete each milestone in order. Studio stores authorization, policy, and decision metadata only; Git work and source code remain on your local machine.</p></header>
    <div className="space-y-3"><Step number="01" title="Confirm the GitHub App boundary" complete={milestones.githubConnected} description="The App must use only Metadata: read and Administration: read. Contents, writes, webhooks, and organization access remain excluded."><div className="rounded-xl border border-white/[0.08] bg-[#0a1116]/65 p-3"><p className="font-mono text-[9px] uppercase tracking-[0.13em] text-[#788d91]">Callback URL for your GitHub App</p><code className="mt-2 block break-all text-xs text-[#dceae3]">{callbackUrl}</code></div><Button onClick={() => beginAuthorization.mutate()} disabled={beginAuthorization.isPending || Boolean(connection.data)} className="mt-3 h-9 rounded-xl bg-[#b7f05a] text-xs font-bold text-[#121a0c] hover:bg-[#c8f87a]">{beginAuthorization.isPending ? <RefreshCw className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Github className="mr-1.5 h-3.5 w-3.5" />}{connection.data ? `Connected as @${connection.data.login}` : "Authorize GitHub App"}</Button></Step>
      <Step number="02" title="Select repositories" complete={milestones.repositoryScopeReady} description="Choose only the repositories whose metadata and default-branch protection posture you want Studio to observe.">{connection.data ? <div className="mt-3 grid gap-2 sm:grid-cols-2">{repositories.data?.map((repository: any) => <button key={repository.id} onClick={() => setSelected.mutate({ repositoryIds: selected.includes(repository.githubRepositoryId) ? selected.filter((id: string) => id !== repository.githubRepositoryId) : [...selected, repository.githubRepositoryId] })} className={`rounded-xl border p-3 text-left ${repository.selected ? "border-[#b7f05a]/30 bg-[#b7f05a]/[0.06]" : "border-white/[0.08] bg-[#0a1116]/55"}`}><div className="flex justify-between gap-2"><span className="text-xs font-semibold text-white">{repository.fullName}</span><Badge variant="outline" className="rounded-full px-2 py-0.5 font-mono text-[8px] uppercase tracking-[0.1em]">{repository.selected ? "selected" : "scope"}</Badge></div><p className="mt-2 text-[11px] text-[#8ca0a1]">Protection: {repository.branchProtectionStatus}</p></button>)}</div> : <Notice text="Authorize GitHub first; then Studio will list only repositories available to the installed App." />}</Step>
      <Step number="03" title="Pair a local companion" complete={milestones.companionPaired} description="The executable companion creates a device key, submits signed metadata, and executes Git locally only after an approved current policy receipt."><div className="mt-3 flex items-center gap-2"><a href="/download" className="inline-flex h-8 shrink-0 items-center whitespace-nowrap rounded-lg border border-[#8cc5ff]/25 bg-[#8cc5ff]/[0.06] px-2.5 text-xs font-medium text-[#b9dcff] transition-colors hover:bg-[#8cc5ff]/[0.12]"><Laptop className="mr-1.5 h-3.5 w-3.5" />Get the CLI</a><span className="text-[11px] leading-4 text-[#829598]">Node 20+ is required for the source bundle.</span></div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input value={label} onChange={event => setLabel(event.target.value)} className="h-9 border-white/[0.1] bg-[#0a1116] text-xs text-white" aria-label="Companion device label" /><Button onClick={() => createPairing.mutate({ label })} disabled={createPairing.isPending} variant="outline" className="h-9 rounded-xl border-white/[0.1] bg-white/[0.03] text-xs text-white hover:bg-white/[0.08]"><KeyRound className="mr-1.5 h-3.5 w-3.5" />Create pairing code</Button></div>{pairing && <div className="mt-3 rounded-xl border border-[#b7f05a]/20 bg-[#b7f05a]/[0.05] p-3"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#bfe879]">Run locally once</p><code className="mt-2 block break-all text-[11px] leading-5 text-[#def7a7]">{pairingCommand}</code><Button onClick={() => copy(pairingCommand)} variant="ghost" className="mt-2 h-8 px-2 text-xs text-[#c9f784] hover:bg-white/[0.05] hover:text-[#dff8a5]"><Copy className="mr-1.5 h-3.5 w-3.5" />Copy command</Button></div>}</Step>
      <Step number="04" title="Confirm the first policy snapshot" complete={milestones.policySyncCurrent} description="Run the companion status command after pairing. It verifies the device-bound policy receipt locally, sends a signed confirmation, then Studio marks the snapshot current."><div className="mt-3 flex flex-wrap items-center gap-2"><Badge variant="outline" className="rounded-full border-[#8cc5ff]/25 bg-[#8cc5ff]/[0.07] px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.1em] text-[#b3d9ff]">{monitoring.data?.summary.currentSnapshots ?? 0} current snapshots</Badge><Button onClick={() => monitoring.refetch()} variant="ghost" className="h-8 px-2 text-xs text-[#a9bdbe] hover:bg-white/[0.05] hover:text-white"><RefreshCw className="mr-1.5 h-3.5 w-3.5" />Check sync status</Button></div></Step>
      <Step number="05" title="Verify signed local status" complete={milestones.localStatusCurrent} description="Send one metadata-only local status check. A fresh check is valid for 15 minutes and is never a substitute for the policy acknowledgement above."><div className="mt-3 rounded-xl border border-white/[0.08] bg-[#0a1116]/65 p-3"><code className="block break-all text-[11px] leading-5 text-[#dceae3]">pnpm companion status --repo /path/to/local/repository --repository-id &lt;studio-repository-id&gt;</code><div className="mt-2 flex flex-wrap items-center gap-2"><Badge variant="outline" className="rounded-full border-[#b7f05a]/25 bg-[#b7f05a]/[0.07] px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.1em] text-[#c9f784]">{monitoring.data?.summary.freshLocalStatuses ?? 0} fresh local checks</Badge><Button onClick={() => monitoring.refetch()} variant="ghost" className="h-8 px-2 text-xs text-[#a9bdbe] hover:bg-white/[0.05] hover:text-white"><RefreshCw className="mr-1.5 h-3.5 w-3.5" />Verify dashboard status</Button></div></div></Step>
    </div>
    <div className="rounded-2xl border border-[#b7f05a]/16 bg-[#b7f05a]/[0.045] p-5"><div className="flex gap-3"><Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-[#c9f784]" /><div><p className="text-sm font-semibold text-white">You are ready when a current policy receipt and no pending high-risk approval are visible in Monitoring.</p><p className="mt-1 text-xs leading-5 text-[#98ab9e]">This keeps automation observable, reviewable, and local-first from the first repository onward.</p></div></div></div>
  </div>;
}

function Step({ number, title, description, complete, children }: { number: string; title: string; description: string; complete: boolean; children: React.ReactNode }) { return <section className={`rounded-[22px] border p-5 ${complete ? "border-[#b7f05a]/20 bg-[#b7f05a]/[0.035]" : "border-white/[0.09] bg-[#101820]/80"}`}><div className="flex gap-4"><div className={`grid h-8 w-8 shrink-0 place-items-center rounded-xl font-mono text-[10px] ${complete ? "bg-[#b7f05a] text-[#17200e]" : "bg-white/[0.06] text-[#8da0a2]"}`}>{complete ? <Check className="h-4 w-4" /> : number}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-base font-bold tracking-[-0.035em] text-white">{title}</h2><SetupMilestoneBadge complete={complete} /></div><p className="mt-1.5 text-xs leading-5 text-[#90a4a5]">{description}</p>{children}</div><ChevronRight className="h-4 w-4 shrink-0 text-[#657a80]" /></div></section>; }
export function SetupMilestoneBadge({ complete }: { complete: boolean }) { return <Badge variant="outline" className={`rounded-full px-2 py-0.5 font-mono text-[8px] uppercase tracking-[0.1em] ${complete ? "border-[#b7f05a]/25 bg-[#b7f05a]/[0.08] text-[#c9f784]" : "border-white/[0.12] text-[#829598]"}`}>{complete ? "complete" : "in progress"}</Badge>; }
function Notice({ text }: { text: string }) { return <div className="mt-3 flex gap-2 rounded-xl border border-[#ffbc7d]/18 bg-[#ffbc7d]/[0.045] p-3 text-xs leading-5 text-[#e3bf9e]"><CircleAlert className="mt-0.5 h-3.5 w-3.5 shrink-0" />{text}</div>; }
