import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { Check, ClipboardCheck, Clock3, Crown, Plus, ShieldCheck, UsersRound, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

export default function TeamApprovals() {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const teams = trpc.team.snapshot.useQuery(undefined, { enabled: isAuthenticated });
  const dashboard = trpc.studio.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const createWorkspace = trpc.team.createWorkspace.useMutation({ onSuccess: () => utils.team.snapshot.invalidate() });
  const setMember = trpc.team.setMember.useMutation({ onSuccess: () => { utils.team.snapshot.invalidate(); toast.success("Team role saved"); }, onError: error => toast.error("Team role could not be saved", { description: error.message }) });
  const saveRule = trpc.team.saveRule.useMutation({ onSuccess: () => { utils.team.snapshot.invalidate(); utils.studio.dashboard.invalidate(); } });
  const decide = trpc.team.decide.useMutation({ onSuccess: () => { utils.studio.dashboard.invalidate(); toast.success("Team decision recorded"); }, onError: error => toast.error("Decision could not be recorded", { description: error.message }) });
  const [workspaceOpen, setWorkspaceOpen] = useState(false);
  const [workspaceName, setWorkspaceName] = useState("Engineering");
  const [memberUserId, setMemberUserId] = useState("");
  const [memberRole, setMemberRole] = useState<"admin" | "reviewer" | "member">("reviewer");
  const workspaces = teams.data?.workspaces ?? [];
  const rules = teams.data?.approvalRules ?? [];
  const workspaceMembers = teams.data?.workspaceMembers ?? [];
  const repositories = dashboard.data?.repositories ?? [];
  const pending = (dashboard.data?.queuedActions ?? []).filter((action: any) => action.status === "pending");
  const selectedRepository = repositories[0];
  const selectedRule = selectedRepository ? rules.find((rule: any) => rule.repositoryId === selectedRepository.id) : undefined;
  const workspace = selectedRule ? workspaces.find((item: any) => item.id === selectedRule.workspaceId) : workspaces[0];
  const [rule, setRule] = useState({ commitRequiresApproval: true, pushRequiresApproval: true, approvalQuorum: 1, allowSelfApproval: false, actionExpiryMinutes: 60 });
  const effectiveRule = useMemo(() => selectedRule ? { ...rule, ...selectedRule } : rule, [selectedRule, rule]);

  const saveApprovalRule = () => {
    if (!selectedRepository || !workspace) return toast.message("Create a workspace and connect a repository first.");
    saveRule.mutate({ repositoryId: selectedRepository.id, workspaceId: workspace.id, ...effectiveRule }, { onSuccess: () => toast.success("Repository approval rule saved") });
  };
  const create = () => createWorkspace.mutate({ name: workspaceName }, { onSuccess: () => { toast.success("Team workspace created"); setWorkspaceOpen(false); }, onError: error => toast.error("Workspace could not be created", { description: error.message }) });
  const saveMember = () => {
    if (!workspace || !/^\d+$/.test(memberUserId)) return toast.message("Enter the existing Studio user ID to assign a role.");
    setMember.mutate({ workspaceId: workspace.id, userId: Number(memberUserId), role: memberRole });
  };

  return <div className="mx-auto max-w-[1180px] space-y-5"><header className="flex flex-col gap-5 border-b border-white/[0.08] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#82949a]">Team approval workflow</p><h1 className="mt-2 text-2xl font-extrabold tracking-[-0.055em] text-white sm:text-[30px]">Human gates for shared code.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#9faeaf]">Require distinct reviewer approvals before a local companion can execute an action. Studio records decisions and policy context; it does not host code or perform Git work.</p></div><Button onClick={() => setWorkspaceOpen(true)} disabled={!isAuthenticated} className="rounded-xl bg-[#b7f05a] text-xs font-bold text-[#121a0c] hover:bg-[#c8f87a]"><Plus className="mr-1.5 h-3.5 w-3.5" />Create workspace</Button></header>
    <section className="grid gap-5 lg:grid-cols-[0.82fr_1.18fr]"><div className="rounded-[24px] border border-white/[0.09] bg-[#101820]/80 p-6"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#778b90]">Your workspaces</p>{workspaces.length ? <div className="mt-5 space-y-3">{workspaces.map((item: any) => <div key={item.id} className="rounded-2xl border border-white/[0.09] bg-[#0b1116]/55 p-4"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#b7f05a]/10 text-[#bdf26a]"><UsersRound className="h-4 w-4" /></div><div><p className="text-sm font-semibold text-white">{item.name}</p><p className="mt-1 text-[11px] text-[#82969a]">Shared policy and review quorum</p></div></div><Badge variant="outline" className="rounded-full border-[#b7f05a]/25 bg-[#b7f05a]/[0.07] px-2 py-1 font-mono text-[9px] uppercase tracking-[0.1em] text-[#c9f784]">Owner</Badge></div></div>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-white/[0.12] bg-[#0b1116]/45 p-5"><Crown className="h-5 w-5 text-[#d7b7ff]" /><p className="mt-3 text-sm font-semibold text-white">Start with a workspace</p><p className="mt-1 text-xs leading-5 text-[#879a9d]">Create a workspace, then assign repository approval rules and invite existing Studio users as administrators, reviewers, or members.</p></div>}</div>
      <div className="rounded-[24px] border border-white/[0.09] bg-[#101820]/80 p-6"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#778b90]">Repository approval rule</p><h2 className="mt-2 text-xl font-bold tracking-[-0.05em] text-white">{selectedRepository ? selectedRepository.name : "Connect a repository first"}</h2>{selectedRepository && workspace ? <div className="mt-6 space-y-5"><div className="grid gap-3 sm:grid-cols-2"><ToggleRule label="Commit review" text="Queue a commit for team review" checked={effectiveRule.commitRequiresApproval} onChange={value => setRule({ ...effectiveRule, commitRequiresApproval: value })} /><ToggleRule label="Push review" text="Require review before remote change" checked={effectiveRule.pushRequiresApproval} onChange={value => setRule({ ...effectiveRule, pushRequiresApproval: value })} /><ToggleRule label="Separate reviewer" text="Do not let the actor approve their own action" checked={!effectiveRule.allowSelfApproval} onChange={value => setRule({ ...effectiveRule, allowSelfApproval: !value })} /><div className="rounded-xl border border-white/[0.08] bg-[#0b1116]/50 p-3"><Label className="text-xs font-semibold text-white">Distinct approvals required</Label><Select value={String(effectiveRule.approvalQuorum)} onValueChange={value => setRule({ ...effectiveRule, approvalQuorum: Number(value) })}><SelectTrigger className="mt-2 h-9 border-white/[0.1] bg-[#0a1015] text-xs text-white"><SelectValue /></SelectTrigger><SelectContent>{[1, 2, 3, 4, 5].map(value => <SelectItem key={value} value={String(value)}>{value} reviewer{value > 1 ? "s" : ""}</SelectItem>)}</SelectContent></Select></div></div><div className="flex items-center justify-between rounded-xl border border-white/[0.08] bg-white/[0.025] p-3"><div className="flex items-center gap-3"><Clock3 className="h-4 w-4 text-[#9bcfff]" /><div><p className="text-xs font-semibold text-white">Action expiry</p><p className="mt-0.5 text-[11px] text-[#82969a]">Fresh policy and metadata are required after this window.</p></div></div><Select value={String(effectiveRule.actionExpiryMinutes)} onValueChange={value => setRule({ ...effectiveRule, actionExpiryMinutes: Number(value) })}><SelectTrigger className="h-9 w-28 border-white/[0.1] bg-[#0a1015] text-xs text-white"><SelectValue /></SelectTrigger><SelectContent>{[15, 30, 60, 120, 240].map(value => <SelectItem key={value} value={String(value)}>{value} min</SelectItem>)}</SelectContent></Select></div><div className="flex justify-end"><Button onClick={saveApprovalRule} disabled={saveRule.isPending} className="rounded-xl bg-[#b7f05a] text-xs font-bold text-[#121a0c] hover:bg-[#c8f87a]"><ShieldCheck className="mr-1.5 h-3.5 w-3.5" />Save approval rule</Button></div></div> : <p className="mt-5 text-sm leading-6 text-[#95a7a9]">Create a workspace and connect a repository before configuring the team review gate.</p>}</div></section>
    <section className="rounded-[24px] border border-white/[0.09] bg-[#101820]/80 p-6"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#778b90]">Approval inbox</p><h2 className="mt-2 text-xl font-bold tracking-[-0.05em] text-white">Actions awaiting a quorum</h2></div><ClipboardCheck className="h-5 w-5 text-[#bdf26a]" /></div>{pending.length ? <div className="mt-5 space-y-3">{pending.map((action: any) => <div key={action.id} className="rounded-2xl border border-white/[0.08] bg-[#0b1116]/50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="text-sm font-semibold text-white">{action.kind === "commit" ? "Commit" : "Push"} · {action.branch}</p><span className={`rounded-full px-2 py-1 font-mono text-[9px] uppercase tracking-[0.1em] ${action.riskLevel === "high" ? "bg-[#ffbb70]/10 text-[#ffc17e]" : "bg-[#b7f05a]/10 text-[#c7f879]"}`}>{action.riskLevel}</span></div><p className="mt-1 text-xs text-[#879a9d]">{action.summary} · {action.changedFiles} changed files</p></div><div className="flex gap-2"><Button onClick={() => decide.mutate({ actionId: action.id, decision: "rejected" })} variant="outline" size="sm" className="rounded-lg border-white/[0.1] bg-white/[0.02] text-xs text-white hover:bg-white/[0.08]"><X className="mr-1 h-3.5 w-3.5" />Reject</Button><Button onClick={() => decide.mutate({ actionId: action.id, decision: "approved" })} size="sm" className="rounded-lg bg-[#b7f05a] text-xs font-bold text-[#121a0c] hover:bg-[#c8f87a]"><Check className="mr-1 h-3.5 w-3.5" />Approve</Button></div></div></div>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-white/[0.11] bg-[#0b1116]/45 p-6 text-center"><Check className="mx-auto h-5 w-5 text-[#bdf26a]" /><p className="mt-3 text-sm font-semibold text-white">No actions await team review</p><p className="mt-1 text-xs leading-5 text-[#879a9d]">When a paired companion submits a policy-compliant action, eligible reviewers can record a distinct decision here.</p></div>}</section>
    <section className="rounded-[24px] border border-white/[0.09] bg-[#101820]/80 p-6"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#778b90]">Team roles</p><h2 className="mt-2 text-xl font-bold tracking-[-0.05em] text-white">Who can approve.</h2></div><UsersRound className="h-5 w-5 text-[#d7b7ff]" /></div>{workspace ? <><div className="mt-5 grid gap-3 md:grid-cols-2">{workspaceMembers.filter((member: any) => member.workspaceId === workspace.id).map((member: any) => <div key={member.id} className="flex items-center justify-between rounded-xl border border-white/[0.08] bg-[#0b1116]/50 p-3"><div><p className="text-sm font-semibold text-white">{member.name}</p><p className="mt-1 font-mono text-[10px] text-[#7f9296]">USER / {member.userId}</p></div><Badge variant="outline" className="rounded-full border-white/[0.12] px-2 py-1 font-mono text-[9px] uppercase tracking-[0.1em] text-[#c8d8d2]">{member.role}</Badge></div>)}</div><div className="mt-5 grid gap-3 rounded-2xl border border-dashed border-white/[0.12] bg-[#0b1116]/45 p-4 sm:grid-cols-[1fr_150px_auto]"><Input type="number" value={memberUserId} onChange={event => setMemberUserId(event.target.value)} placeholder="Existing Studio user ID" className="border-white/[0.1] bg-[#0a1015] text-xs text-white" /><Select value={memberRole} onValueChange={value => setMemberRole(value as "admin" | "reviewer" | "member")}><SelectTrigger className="border-white/[0.1] bg-[#0a1015] text-xs text-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="admin">Administrator</SelectItem><SelectItem value="reviewer">Reviewer</SelectItem><SelectItem value="member">Member</SelectItem></SelectContent></Select><Button onClick={saveMember} disabled={setMember.isPending} className="rounded-xl bg-white/[0.09] text-xs text-white hover:bg-white/[0.15]">Save role</Button></div><p className="mt-2 text-[11px] leading-5 text-[#82969a]">Members must already have a Studio account. Owners and administrators may update administrator, reviewer, and member roles; the owner role cannot be overwritten here.</p></> : <p className="mt-5 text-sm leading-6 text-[#95a7a9]">Create a workspace to assign reviewer and administrator roles.</p>}</section>
    <Dialog open={workspaceOpen} onOpenChange={setWorkspaceOpen}><DialogContent className="border-white/[0.12] bg-[#101820] text-white sm:max-w-[440px]"><DialogHeader><DialogTitle className="text-xl font-extrabold tracking-[-0.05em]">Create team workspace</DialogTitle><DialogDescription className="leading-6 text-[#92a4a5]">Workspaces coordinate Studio roles and approval rules. They do not grant GitHub or local machine access.</DialogDescription></DialogHeader><div className="py-3"><Label className="text-xs text-[#d9e5df]">Workspace name</Label><Input value={workspaceName} onChange={event => setWorkspaceName(event.target.value)} className="mt-2 border-white/[0.1] bg-[#0a1015] text-white" /></div><DialogFooter><Button variant="ghost" onClick={() => setWorkspaceOpen(false)} className="text-[#9aadae] hover:bg-white/[0.06] hover:text-white">Cancel</Button><Button onClick={create} disabled={createWorkspace.isPending} className="rounded-xl bg-[#b7f05a] text-xs font-bold text-[#121a0c] hover:bg-[#c8f87a]">Create workspace</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function ToggleRule({ label, text, checked, onChange }: { label: string; text: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between rounded-xl border border-white/[0.08] bg-[#0b1116]/50 p-3"><div className="pr-3"><p className="text-xs font-semibold text-white">{label}</p><p className="mt-1 text-[11px] leading-4 text-[#82969a]">{text}</p></div><Switch checked={checked} onCheckedChange={onChange} /></div>; }
