// Vercel function entrypoint. The referenced bundle is generated by the
// repository build command before Vercel traces serverless dependencies.
import app from "../dist/vercel.js";

export default app;
